services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-noise
    ports:
      - "1314:1314"
    volumes:
      - ./data:/app/data
    environment:
      - LOG_LEVEL=info
      - DATABASE_FILE=/app/data/noise.db
    restart: unless-stopped