version: "3.8"

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-noise
    ports:
      - "1314:1314"
    volumes:
      - ./data:/app/data
    environment:
      - CGO_ENABLED=1
    restart: always
